github:
  org: archway-network
  repo: networks
  dir: _IBC
  testnetsDir: testnets/_IBC
rpc:
  # mainnets
  - chainName: archway
    chainId: archway-1
    url: https://rpc.mainnet.internal.archway.io:443
  - chainName: agoric
    chainId: agoric-3
    url: https://main.rpc.agoric.net:443
  - chainName: axelar
    chainId: axelar-dojo-1
    url: https://axelar-rpc.quickapi.com:443
  - chainName: bitcanna
    chainId: bitcanna-1
    url: https://rpc.bitcanna.io:443
  - chainName: cosmoshub
    chainId: cosmoshub-4
    url: https://cosmos-rpc.quickapi.com:443
  - chainName: decentr
    chainId: mainnet-3
    url: https://rpc.decentr.chaintools.tech:443
  - chainName: jackal
    chainId: jackal-1
    url: https://jackal.rpc.kjnodes.com:443
  - chainName: juno
    chainId: juno-1
    url: https://juno-rpc.publicnode.com:443
  - chainName: kujira
    chainId: kaiyo-1
    url: https://kujira-rpc.publicnode.com:443
  - chainName: noble
    chainId: noble-1
    url: https://noble-rpc.polkachu.com:443
  - chainName: nois
    chainId: nois-1
    url: https://rpc.nois.silentvalidator.com:443
  - chainName: omniflixhub
    chainId: omniflixhub-1
    url: https://omniflix-rpc.dakshavalidator.in:443
  - chainName: osmosis
    chainId: osmosis-1
    url: https://rpc-osmosis.ecostake.com:443
  - chainName: quicksilver
    chainId: quicksilver-2
    url: https://rpc.quicksilver.zone:443
  - chainName: umee
    chainId: umee-1
    url: https://umee-rpc.polkachu.com:443
  - chainName: gravitybridge
    chainId: gravity-bridge-3
    url: https://gravity-rpc.polkachu.com:443
  - chainName: secretnetwork
    chainId: secret-4
    url: https://rpc.mainnet.secretsaturn.net:443
  - chainName: terra2
    chainId: phoenix-1
    url: https://terra-rpc.stakely.io:443
  - chainName: comdex
    chainId: comdex-1
    url: https://rpc.comdex.one:443
  - chainName: neutron
    chainId: neutron-1
    url: https://rpc-voidara.neutron-1.neutron.org:443
  - chainName: qwoyn
    chainId: qwoyn-1
    url: https://rpc-qwoyn.theamsolutions.info:443
  - chainName: stargaze
    chainId: stargaze-1
    url: https://rpc.stargaze.silentvalidator.com:443
  - chainName: andromeda
    chainId: andromeda-1
    url: https://andromeda.rpc.kjnodes.com:443
  - chainName: pylons
    chainId: pylons-mainnet-1
    url: https://rpc.nodejumper.io:443/pylons
  - chainName: injective
    chainId: injective-1
    url: https://injective-rpc.publicnode.com:443
  - chainName: dydx
    chainId: dydx-mainnet-1
    url: https://rpc-dydx.ecostake.com:443
  - chainName: akash
    chainId: akashnet-2
    url: https://rpc-akash.ecostake.com:443
  - chainName: cudos
    chainId: cudos-1
    url: https://cudos-rpc.lavenderfive.com:443
  - chainName: celestia
    chainId: celestia
    url: https://celestia-rpc.enigma-validator.com:443
  - chainName: evmos
    chainId: evmos_9001-2
    url: https://rpc-evmos-01.stakeflow.io:443
  - chainName: stride
    chainId: stride-1
    url: https://stride-rpc.polkachu.com:443
  - chainName: persistence
    chainId: core-1
    url: https://persistence-rpc.publicnode.com:443
  - chainName: composable
    chainId: centauri-1
    url: https://composable-mainnet-rpc.autostake.com:443
  - chainName: empowerchain
    chainId: empowerchain-1
    url: https://rpc-empowerchain.mzonder.com:443
  - chainName: planq
    chainId: planq_7070-2
    url: https://rpc.planq.network:443
  - chainName: passage
    chainId: passage-2
    url: https://passage-rpc.polkachu.com:443
  - chainName: sentinel
    chainId: sentinelhub-2
    url: https://rpc-sentinel.chainvibes.com:443
  - chainName: dymension
    chainId: dymension_1100-1
    url: https://dymension-rpc.ibs.team:443
  - chainName: bitsong
    chainId: bitsong-2b
    url: https://rpc.explorebitsong.com:443
  - chainName: coreum
    chainId: coreum-mainnet-1
    url: https://coreum-rpc.ibs.team:443
  - chainName: nibiru
    chainId: cataclysm-1
    url: https://nibiru.rpc.kjnodes.com:443

  # testnets
  - chainName: archwaytestnet
    chainId: constantine-3
    url: https://rpc.constantine.archway.io:443
  - chainName: axelartestnet
    chainId: axelar-testnet-lisbon-3
    url: https://rpc-axelar-testnet.imperator.co:443
  - chainName: osmosistestnet
    chainId: osmo-test-5
    url: https://rpc-1.testnet.osmosis.nodes.guru:443
  # - chainName: nobletestnet
  #   chainId: grand-1
  #   url: https://noble-testnet-rpc.polkachu.com:443
accounts:
  # foundation-feegrant-astrovault
  - address: archway1gpyqzc0aerc85cpk2cm8ec6zkc95x5yqrakskv
    chainName: archway
    denom: aarch
  # foundation-feegrant-ojo
  - address: archway1c2cu99uzjauaj5hg45edhzgsk5saz43y6d3zxp
    chainName: archway
    denom: aarch
  # PhiLabs
  - address: archway1ktka5q3cnsy3ar7qwj2huzz6qj9q4ys7h74l9y
    chainName: archway
    denom: aarch
  - address: archway1avwvqzu9gv86g5fxx5p2xqe0w33wklt27jusdrhszwccnfnxx0rsmzz8nu
    chainName: archway
    denom: aarch
